// src/hooks/faults.config.js

export const FAULT_CATEGORIES = {
  "Battery Faults": [
    "BPeakRegenOverCurr30sAlarm",
    "BContChargingOverCurrAlarm",
    "BPeakOverDischCurr30sAlarm",
    "BContOverDischCurrAlarm",
    "BCellOverVoltAlarm",
    "BCellUnderVoltAlarm",
    "BCellOverTempAlarm",
    "BCellUnderTempAlarm",
    "BPackOverVoltAlarm",
    "BPackUnderVoltAlarm",
    "BCellvoltsamplingAlarm",
    "BCelltempsamplingAlarm",
    "BSOCLowAlarm",
    "BCoolantLeakagesensorAlarm",
    "BAllContactorFlt",
    "BCellDVStaticAlarm",
    "BLowSOHAlarm",
    "BSlaveCommLossAlarm",
    "BHVILAlarm",
    "BPosContactorHwFlt",
    "BNegContactorHwFlt",
    "BNegContactorWeldFlt",
    "BVCUBMSCommFlt",
    "BPackVoltSamplingflt",
    "BTempSensorHwFlt",
    "BPack2PackCommFlt",
    "BPackBalancingHwFlt",
    "BCurrSensorHwFlt",
    "BThermalRunawayFlt",
    "BThermalSensorHWFlt",
    "BCellDeltaTempertureAlarm",
    "BCellBalancingHwFlt",
    "BPackVoltMismatchFlt",
    "BCellDVDynAlarm",
    "BVCUBMSCRCFailureFlt",
    "BPrechargeFlt",
    "BInsulationDetectionFlt",
    "BSOHZeroFlt",
    "BSlaveCommLossAlarm",
    "ASlaveCommLossSlaveNo",
    "APeakRegenOverCurr30sAlarm",
    "AContChargingOverCurrAlarm",
    "APeakOverDischCurr30sAlarm",
    "AContOverDischCurrAlarm",
    "ACellOverVoltAlarm",
    "ACellUnderVoltAlarm",
    "ACellOverTempAlarm",
    "ACellUnderTempAlarm",
    "APackOverVoltAlarm",
    "APackUnderVoltAlarm",
    "ACellvoltsamplingAlarm",
    "ACelltempsamplingAlarm",
    "ASOCLowAlarm",
    "ASlaveCommLossAlarm",
    "AAllContactorFlt",
    "ACellDVStaticAlarm",
    "ALowSOHAlarm",
    "AHVILAlarm",
    "APosContactorHwFlt",
    "APosContactorWeldFlt",
    "ANegContactorHwFlt",
    "ANegContactorWeldFlt",
    "AVCUBMSCommFlt",
    "APackVoltSamplingflt",
    "ACurrSensorHwFlt",
    "ATempSensorHwFlt",
    "APack2PackCommFlt",
    "APackBalancingHwFlt",
    "AThermalSensorHWFlt",
    "ACellDeltaTempertureAlarm",
    "ACellBalancingHwFlt",
    "APackVoltMismatchFlt",
    "ACellDVDynAlarm",
    "AVCUBMSCRCFailureFlt",
    "APrechargeFlt",
    "AInsulationDetectionFlt",
    "ASOHZeroFlt",
    "AThermalRunawayFlt",
    "BSlaveCommLossSlaveNo",
    "ACoolantLeakagesensorAlarm",
  ],
  "MCU Faults": ["MCUfault"],
  "DCDC Faults": [
    "DCDCfault",
    "DCDCINPUTUndervolt",
    "DCDCINPUTOvervolt",
    "DCDCLowvoltpowersupplyUV",
    "DCDCLowvoltpowersupplyOV",
    "DCDCOutputUV",
    "DCDCOutputOvervolt",
    "DCDCEXTERNALENBFAULT",
    "DCDCSHIMinductorUndertemp",
    "DCDCSHIMinductorOvertemp",
    "DCDCTransformerUndertemp",
    "DCDCTransformerOvertemp",
    "DCDCSecondarymosfetUndertemp",
    "DCDCSecondarymosfetovertemp",
    "DCDCPrimarymosfetUndertemp",
    "DCDCPrimarymosfetOvertemp",
    "DCDCHVILFAULT",
    "InHVACfault",
    "PhaseshiftfullbridgeFAULT",
  ],
  "BCS Fault": ["BCSfault"],
  "TCS Fault": [
    "TCSfault",
    "PumpFaultLevel",
    "PumpOvercurrentFault",
    "PumpOverVoltageFault",
  ],
  "EVCC Fault": ["EVCCfault"],
  "EBS Fault": ["BrakeTemperatureHigh"],
  "ECAS Fault": ["EBSfault", "ECASfault"],
};